# Generated by Django 3.0.4 on 2020-03-25 14:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('polls', '0002_album_musician_personc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fruit',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
    ]
